/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filtering;

import BigData.Bigdata;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author herrerach_sd2082
 */
public class JFrame_Timer extends javax.swing.JFrame {

    static boolean state = true;
    static int seconds = 0;
    static int minutes = 0;
    static int hours = 0;

    /**
     * Creates new form JFrame_Timer
     */
    public JFrame_Timer() {
        initComponents();
        Seconds.setEnabled(false);
        Minutes.setEnabled(false);
        Hour.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hour1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Stop_Button = new javax.swing.JButton();
        Start_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Seconds = new javax.swing.JLabel();
        Hour = new javax.swing.JLabel();
        Minutes = new javax.swing.JLabel();

        Hour1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Hour1.setForeground(new java.awt.Color(252, 35, 156));
        Hour1.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(252, 35, 156));

        jPanel1.setBackground(new java.awt.Color(10, 1, 6));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 35, 156));
        jLabel1.setText("STOPWATCH");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 35, 156));
        jLabel4.setText("HOUR");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 35, 156));
        jLabel5.setText("MINUTES");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 35, 156));
        jLabel6.setText("SECONDS");

        Stop_Button.setBackground(new java.awt.Color(10, 1, 6));
        Stop_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Stop_Button.setForeground(new java.awt.Color(252, 35, 156));
        Stop_Button.setText("STOP");
        Stop_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Stop_ButtonMouseClicked(evt);
            }
        });
        Stop_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stop_ButtonActionPerformed(evt);
            }
        });

        Start_Button.setBackground(new java.awt.Color(10, 1, 6));
        Start_Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Start_Button.setForeground(new java.awt.Color(252, 35, 156));
        Start_Button.setText("START");
        Start_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Start_ButtonMouseClicked(evt);
            }
        });
        Start_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_ButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(252, 35, 156));
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 35, 156));
        jLabel3.setText(":");

        Seconds.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Seconds.setForeground(new java.awt.Color(252, 35, 156));
        Seconds.setText("00");

        Hour.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Hour.setForeground(new java.awt.Color(252, 35, 156));
        Hour.setText("0");

        Minutes.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Minutes.setForeground(new java.awt.Color(252, 35, 156));
        Minutes.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Hour)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(Minutes)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Seconds)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(62, 62, 62))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(Start_Button)
                .addGap(82, 82, 82)
                .addComponent(Stop_Button)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Seconds)
                            .addComponent(Minutes))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Hour))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start_Button)
                    .addComponent(Stop_Button))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Stop_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stop_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop_ButtonActionPerformed

    private void Start_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Start_ButtonActionPerformed

    private void Start_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Start_ButtonMouseClicked
        state = true;

        Thread thread = new Thread() {

            @Override
            public void run() {
                for (;;) {
                    if (state == true) {
                        try {
                            sleep(1000);
                            if (seconds == 59) {
                                minutes++;
                                seconds = 0;
                            }
                            if (minutes == 60) {
                                hours++;
                                minutes = 0;
                                seconds = 0;
                            }
                            seconds++;
                            Minutes.setText(String.valueOf(minutes));
                            Seconds.setText(String.valueOf(seconds));
                            Hour.setText(String.valueOf(hours));

                        } catch (InterruptedException ex) {
                            Logger.getLogger(Bigdata.class
                                    .getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            }

        };

        thread.start();
    }//GEN-LAST:event_Start_ButtonMouseClicked

    private void Stop_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Stop_ButtonMouseClicked
        state = false;
    }//GEN-LAST:event_Stop_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Timer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Timer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Timer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Timer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hour;
    private javax.swing.JLabel Hour1;
    private javax.swing.JLabel Minutes;
    private javax.swing.JLabel Seconds;
    private javax.swing.JButton Start_Button;
    private javax.swing.JButton Stop_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
